### ISSUE TITLE
how to get the error detail 

### ISSUE THREAD

**Issue by songsongMr** [espritblock/eos4j#2]
all the describe of error is   "io.eblock.eos4j.api.exception.ApiException: Internal Service Error" ,how to get the  error detail
exp:
try {
Transaction t1 = rpc.transfer("5Ka2MNvrtWfNDueCvt4yBMSoKNMNdnL8bcdv94PkgJhpxvTr3Uo","eosio.token", "eosio.token","lishi12", "12.2821 EOS", ""); 
}catch(Exception ex) {
 			ex.printStackTrace();
//"io.eblock.eos4j.api.exception.ApiException: Internal Service Error
			 
		}

**Comment by espritblock** [comment]
Update code
try{
}catch(ApiException ex){
   ex.getError()
}
