### ISSUE TITLE
使用手机进行pushTransaction出现 unsatisfied_authorization 3090003 错误

### ISSUE THREAD

**Issue by JIAN006** [espritblock/eos4j#21]
同样的代码,在pc使用java直接进行转账是成功的,但是放在手机上跑就失败了

**Comment by samkirton** [comment]
Please see https://github.com/memtrip/eos-jvm as an alternative EOS SDK.

**Comment by JIAN006** [comment]
> 请参阅https://github.com/memtrip/eos-jvm作为替代EOS SDK。

OK,I will use this SDK

**Comment by JIAN006** [comment]
> Please see https://github.com/memtrip/eos-jvm as an alternative EOS SDK.

OK,I will use this SDK,thanks
