### ISSUE TITLE
转账精度问题

### ISSUE THREAD

**Issue by shrimpliu** [espritblock/eos4j#6]
转账方法的 asset 序列化时，把 amount 处理成整数时，没有考虑小数点后位数超过 4 的情况，导致如果传的金额是 '100.12345 EOS' 时，转成的整数变成 '10012345', 而不是 '1001234'。
问题代码[在这里](https://github.com/espritblock/eos4j/blob/394e8db508930c945f0eb1bc4603ca403789d12a/src/main/java/io/eblock/eos4j/utils/ByteUtils.java#L170)

**Comment by espritblock** [comment]
感谢你提交的issues，问题已经修复，请更新代码，调用前请严格校验参数
